name: course_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  auto_route: ^8.1.3
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  sizer: ^2.0.15
  dio: ^5.4.3+1
  fpdart: ^1.1.0
  syncfusion_flutter_gauges: ^25.2.4
  video_player: ^2.8.6
  flutter_sticky_widgets: ^0.0.3
  html: ^0.15.4
  meta: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.10

flutter:
  uses-material-design: true
